---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: monitoring
spec:
  parentRefs:
    - name: monitoring-gateway
      kind: Gateway
      sectionName: http
      group: gateway.networking.k8s.io
  hostnames:
    - prometheus.raft.lutris.house
  rules:
    - backendRefs:
        - name: prometheus-stack-kube-prom-prometheus
          port: 9090
          kind: Service
          group: ""
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
