---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ergo-server
  namespace: ergo-irc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ergo
  template:
    metadata:
      labels:
        name: ergo
    spec:
      containers:
        - name: ergo-server-ctr
          ports:
            - containerPort: 6667
              name: irc
              protocol: TCP
            - containerPort: 6697
              name: irc-tls
              protocol: TCP
          image: ghcr.io/ergochat/ergo:stable
          volumeMounts:
            - name: ergo-data
              mountPath: /ircd
            - name: tls-certs
              mountPath: /ircd/tls
      volumes:
        - name: ergo-data
          persistentVolumeClaim:
            claimName: ergo-data-pvc
        - name: tls-certs
          secret:
            secretName: irc-certificate
